"use client";

import { useEffect, useState } from "react";
import { fetchHistory } from "@/lib/api";
import { RiskBadge } from "@/components/RiskBadge";
import { Loader2, Database, Clock } from "lucide-react";

export default function HistoryPage() {
  const [history, setHistory] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    try {
      const data = await fetchHistory();
      setHistory(data.history || []);
    } catch (err) {
      console.error(err);
      setError("Failed to load clinical history from the backend.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="glass-card rounded-xl p-6 border-b-4 border-b-[var(--primary)]">
        <div className="flex items-center gap-3 mb-2">
          <Database className="w-6 h-6 text-[var(--primary)]" />
          <h1 className="text-2xl font-bold tracking-tight text-slate-800">Clinical Audit Log</h1>
        </div>
        <p className="text-sm text-slate-500 max-w-2xl">
          Historical records of all patient risk assessments generated by the ImmunoPredict Hybrid AI engine.
        </p>
      </div>

      <div className="glass-card rounded-xl overflow-hidden">
        {isLoading ? (
          <div className="h-64 flex flex-col items-center justify-center text-slate-400">
            <Loader2 className="w-8 h-8 mb-4 animate-spin text-[var(--primary)]" />
            <span>Fetching secure records...</span>
          </div>
        ) : error ? (
          <div className="h-64 flex items-center justify-center text-red-500 font-medium p-6 text-center">
            {error}
          </div>
        ) : history.length === 0 ? (
          <div className="h-64 flex items-center justify-center text-slate-500">
            No historical predictions found in the database.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-600 uppercase text-xs font-semibold border-b">
                <tr>
                  <th className="px-6 py-4">Timestamp</th>
                  <th className="px-6 py-4">Patient ID</th>
                  <th className="px-6 py-4">Age / Sex / BMI</th>
                  <th className="px-6 py-4">Day 28 Titer (Predicted)</th>
                  <th className="px-6 py-4">Clinical Risk Assessment</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {history.map((record) => (
                  <tr key={record.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap text-slate-500 flex items-center gap-2">
                      <Clock className="w-3 h-3" />
                      {new Date(record.created_at).toLocaleString()}
                    </td>
                    <td className="px-6 py-4 font-mono font-medium text-[var(--primary)]">
                      {record.patient_id}
                    </td>
                    <td className="px-6 py-4 text-slate-600">
                      {record.age} yr / {record.sex === 0 ? 'M' : 'F'} / {record.bmi}
                    </td>
                    <td className="px-6 py-4 font-semibold text-slate-800">
                      {record.predicted_titer_28.toFixed(1)} <span className="text-[10px] text-slate-400 font-normal">IU/mL</span>
                    </td>
                    <td className="px-6 py-4">
                      <RiskBadge tier={record.risk_tier} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
